name: Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']
        moodle-branch: ['MOODLE_405_STABLE', 'master']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, mysqli, gd, xml, dom, json, zip, bcmath, intl
          ini-values: max_execution_time=600, memory_limit=1G

      - name: Install Moodle Plugin CI (Force Isolation)
        run: |
          # Criamos uma pasta isolada e forçamos o Composer a ignorar o projeto local
          mkdir ~/moodle-plugin-ci
          cd ~/moodle-plugin-ci
          # O comando COMPOSER="" limpa qualquer configuração que venha do seu plugin
          COMPOSER="" composer require "moodlehq/moodle-plugin-ci:^4" --no-interaction --ignore-platform-reqs
          echo "$HOME/moodle-plugin-ci/vendor/bin" >> $GITHUB_PATH

      - name: Initialize CI
        run: |
          moodle-plugin-ci install --plugin . --moodle-branch ${{ matrix.moodle-branch }}

      - name: Run PHPCS
        run: moodle-plugin-ci phpcs

      - name: Run PHPUnit
        run: moodle-plugin-ci phpunit
        