name: Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false # Não para todos os testes se um falhar
      matrix:
        # Testando nas versões que o Moodle 4.5/5.1 exigem
        php: ['8.2', '8.3']
        moodle-branch: ['MOODLE_405_STABLE', 'master']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, mysqli, gd, xml, dom, json, zip, bcmath, intl
          ini-values: max_execution_time=600, memory_limit=1G

      - name: Install Moodle Plugin CI
        run: |
          # Instalando com a bandeira de ignorar requisitos de plataforma para evitar o erro 2
          composer global require "moodlehq/moodle-plugin-ci:^4" --no-interaction --ignore-platform-reqs
          echo "$(composer global config bin-dir --absolute)" >> $GITHUB_PATH

      - name: Initialize CI
        run: |
          moodle-plugin-ci install --plugin . --moodle-branch ${{ matrix.moodle-branch }}

      - name: Run PHPCS
        run: moodle-plugin-ci phpcs

      - name: Run PHPUnit
        run: moodle-plugin-ci phpunit
        