name: PlayerHUD PHPUnit Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      # fail-fast: false faz com que, se o teste falhar no Moodle 4.5,
      # ele continue testando no 5.0 e 5.1 para você ver o cenário completo.
      fail-fast: false
      matrix:
        moodle-branch: ['MOODLE_405_STABLE', 'MOODLE_500_STABLE', 'MOODLE_501_STABLE']
        php: ['8.2', '8.3']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, mysqli, pgsql, xmlrpc, soap, gd, xml, intl, sodium, curl, zip, zlib

      - name: Install moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4.0
          export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

      - name: Install Moodle and Plugin
        run: |
          export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
          moodle-plugin-ci install --plugin ./ --db-host=127.0.0.1 --moodle ${{ matrix.moodle-branch }}

      - name: Run PHPUnit
        run: |
          export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
          moodle-plugin-ci phpunit
